### ISSUE TITLE
undefined method `authorize' when bin/spring is running

### ISSUE THREAD

**Issue by MarcoBatista** [RailsApps/rails-devise-pundit#10]
I installed railsApps, rails+devise+pundit, after register an user and when list all users, I have this error.

undefined method `authorize' for #<UsersController

  def index
    @users = User.all
   ->  authorize User <- 
  end

**Comment by mtrolle** [comment]
@vjm Cool - helped do include Pundit in the ApplicationController - thanks!

**Comment by cweilemann** [comment]
I'm seeing this running rspec.  Stopping and restarting spring seems to work for one round of spec tests...  So, does this mean that the *permanent* solution is to move the pundit initializer code to the ApplicationController for both development and test?

**Comment by benjaminsigidi** [comment]
I think that's the best solution.

**Comment by serodriguez68** [comment]
@vjm 's solution works fine.  However I would like to know why are there performance benefits by using an initializer instead of just moving all to the application controller permanently?

**Comment by rlabuonora** [comment]
Same problem here. I tried restarting the server, stopping spring, and moving the code from  initializers/pundit.rb to the application controller.

Nothing worked. Any ideas?

**Comment by rlabuonora** [comment]
Ok, I just had to put the line:

include Pundit at the top of ApplicationController as per the first answer to [this question](http://stackoverflow.com/questions/27237173/undefined-method-authorize-with-pundit)

**Comment by swiknaba** [comment]
This issue occurred for me with rails 5.1.6 a while ago. Upgrading to 5.2.1 solved the problem (well, now you probably want to try 5.2.2).
