### ISSUE TITLE
RAILS_ENV=production rake assets:precompile - Failed to precompile

### ISSUE THREAD

**Issue by studiorooster** [RailsApps/rails-devise-pundit#17]
I have been fighting with this for hours and I cannot get the app to pre-compile.  It works great on my local environment, but I am trying to push it up to Heroku, but everytime I run 'RAILS_ENV=production rake assets:precompile' I get the below error.  Any help would be great.  Thank you.

' charles@rooster:~/apps/cfi-app$ RAILS_ENV=production rake assets:precompile
rake aborted!
TypeError: no implicit conversion of nil into String
/home/charles/apps/cfi-app/config/initializers/devise.rb:13:in `+'
/home/charles/apps/cfi-app/config/initializers/devise.rb:13:in`block in <top (required)>'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/devise-3.2.4/lib/devise.rb:288:in `setup'
/home/charles/apps/cfi-app/config/initializers/devise.rb:3:in`<top (required)>'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `load'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in`block in load'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in`load'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/railties-4.1.4/lib/rails/engine.rb:648:in `block in load_config_initializer'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/activesupport-4.1.4/lib/active_support/notifications.rb:161:in`instrument'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/railties-4.1.4/lib/rails/engine.rb:647:in `load_config_initializer'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/railties-4.1.4/lib/rails/engine.rb:612:in`block (2 levels) in class:Engine'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/railties-4.1.4/lib/rails/engine.rb:611:in `each'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/railties-4.1.4/lib/rails/engine.rb:611:in`block in class:Engine'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/railties-4.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/railties-4.1.4/lib/rails/initializable.rb:30:in`run'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/railties-4.1.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/railties-4.1.4/lib/rails/initializable.rb:44:in`each'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/railties-4.1.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/railties-4.1.4/lib/rails/initializable.rb:54:in`run_initializers'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/railties-4.1.4/lib/rails/application.rb:300:in `initialize!'
/home/charles/apps/cfi-app/config/environment.rb:5:in`<top (required)>'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in`block in require'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in`require'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/railties-4.1.4/lib/rails/application.rb:276:in `require_environment!'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/railties-4.1.4/lib/rails/application.rb:379:in`block in run_tasks_blocks'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:55:in `block (2 levels) in define'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/bin/ruby_executable_hooks:15:in`eval'
/home/charles/.rvm/gems/ruby-2.1.0@cfi-app/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)'

**Comment by goldnuggets24** [comment]
Thanks @DanielKehoe !! Helped me out quite a bit this afternoon.
