### ISSUE TITLE
names aren't being saved

### ISSUE THREAD

**Issue by MaxPleaner** [RailsApps/rails-devise-pundit#20]
I ran the app from composer and additionally installed devise invitable. using ruby 2.1.4 and rails 4.1.7. This composer is amazing and thank you so much. The problem is user names aren't being saved to db. I ran the RailsApp Templates generator for devise and can see in the form params that the name is included with submission. However, it is lost at some point during the email-confirmation process and remains `nil` in the database. 

I am not sure how to go in and fix this problem. There's a not a `User.create(user_params)` like I'm used to so I don't know where the attribute is actually being (unsuccessfully) applied. Editing the user name once logged in does not save either.

**Comment by DanielKehoe** [comment]
What was the cause of the problem? Can you comment further?
