### ISSUE TITLE
Error thrown at the end of the install script

### ISSUE THREAD

**Issue by fegul** [RailsApps/rails-devise-pundit#21]
The script for the app throws an error during generation and it doesn't seem to work with any combination. The step and resulting error is:

Step:
`extras  recipe creating project-specific rvm gemset and .rvmrc`

Error:
    /home/user/.rvm/gems/ruby-2.2.0@global/gems/rvm-     1.11.3.9/lib/rvm/shell/abstract_wrapper.rb:139:in `raw_stdout_to_parts': private method `load' called     for Psych:Module (NoMethodError)'

**Comment by DanielKehoe** [comment]
If you have an error with the Rails Composer script, open an issue here: https://github.com/RailsApps/rails-composer/issues
